name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        working-directory: vroom-frontend
      - name: Build the project
        run: npm run build
        working-directory: vroom-frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Update Render service branch
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          if [ "${{ github.ref_name }}" == "main" ] || [ "${{ github.ref_name }}" == "dev" ]; then
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_DEV }}
            BRANCH="dev"
          else
            SERVICE_ID=${{ secrets.RENDER_SERVICE_ID_FEATURE }}
            BRANCH="${{ github.head_ref }}"
          fi

          curl --request PATCH \
            --url https://api.render.com/v1/services/$SERVICE_ID \
            --header 'accept: application/json' \
            --header 'content-type: application/json' \
            --header "Authorization: Bearer $RENDER_API_KEY" \
            --data '{"branch":"'"$BRANCH"'"}'

      - uses: actions/checkout@v3
      - name: Deploy to Render (Main)
        if: github.ref_name == 'main'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_DEV }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
      - name: Deploy to Render (Dev)
        if: github.ref_name == 'dev'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_DEV }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
      - name: Deploy to Render (Feature)
        if: github.ref_name != 'main' && github.ref_name != 'dev'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_FEATURE }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
