name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        working-directory: vroom-frontend
      - name: Build the project
        run: npm run build
        working-directory: vroom-frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Render (Main)
        if: github.ref_name == 'main'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_DEV }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          branch: dev
      - name: Deploy to Render (Dev)
        if: github.ref_name == 'dev'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_DEV }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          branch: dev
      - name: Deploy to Render (Feature)
        if: github.ref_name != 'main' && github.ref_name != 'dev'
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_FEATURE }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          branch: ${{ github.ref_name }}
